### ISSUE TITLE
Openblas and reference lapack license violation in r-base=3.5.1

### ISSUE THREAD

**Issue by isuruf** [conda-forge/r-base-feedstock#101]
Please package the licenses for openblas and reference lapack for r-base=3.5.1, as they are mandatory.

**Comment by isuruf** [comment]
cc @conda-forge/core, please pull r-base=3.5.1 if this is not resolved soon.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/r-base-feedstock/pull/102

**Comment by jdblischak** [comment]
@isuruf Thanks for fixing this!
