### ISSUE TITLE
Packages require rebuilding with conda-build > 2.0

### ISSUE THREAD

**Issue by lparsons** [conda-forge/r-base-feedstock#12]
I've run into an issues with a couple of packages (from the `r` channel) which give me the error:

```
PaddingError: Placeholder of length '80' too short in package [channel]::[package]
The package must be rebuilt with conda-build > 2.0.
```

While these are coming from the `r` channel, I believe this is the new home for these packages? Or at least could be?

The packages are:
- [ ] `r::r-base-3.2.1-0`
- [ ] `r::r-base-3.2.2-0`

**Comment by jakirkham** [comment]
So if they were our R packages (no pun intended), they would be called `conda-forge::r-base...`. As this is not the case and as `r` is an Anaconda maintained channel, I'll refer you to Anaconda's recipe issue tracker. Hopefully that will get you closer to someone that can help.

**Comment by jakirkham** [comment]
This issue was moved to ContinuumIO/anaconda-recipes#88
