### ISSUE TITLE
Missing import libraries

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/r-base-feedstock#17]
It seems that the mingw64 build does not include the import libraries (`.dll.a` or `.a`) required to link external libraries with R.

cc @mingwandroid

**Comment by mingwandroid** [comment]
I'll try to look into this at next rebuild. I worked around it when I needed import libraries:

https://github.com/mingwandroid/conda-recipes/blob/master/rstudio/bld.bat#L34-L52

This generates MSVC ones, but getting mingw-w64 ones is pretty similar.

**Comment by SylvainCorlay** [comment]
Hum, oddly, official builds don't have the import libraries either, so it may not be a good idea have conda users expect them.

**Comment by mingwandroid** [comment]
I didn't change the build system for R significantly so this does not surprise me.

It may be worth filling a bug upstream it at least along the question on the mailing list? Thing is, GCC can link to DLLs directly anyway.
