### ISSUE TITLE
Prepare for R 4.1

### ISSUE THREAD

**Issue by izahn** [conda-forge/r-base-feedstock#170]
[R 4.1 is scheduled for release on May 18th 2021](https://developer.r-project.org/
). Is there anything we need to do to prepare for that? I'm happy to help, but not sure what (if anything) needs to be done!

**Comment by jdblischak** [comment]
@izahn The bot opened its automated PR (#173) to bump the version to 4.1.0. All the jobs are currently failing, so there's probably plenty to work on. Any help is super appreciated. Thanks!

**Comment by izahn** [comment]
Thanks @jdblischak , happy to work on getting r-base to build. Is there more to it then that? Do we need to rebuild all the packages with R 4.1?

**Comment by dpryan79** [comment]
Yes, there will have to be a migration that takes place, with r-base 3.6 being dropped from conda-forge-pinning.

**Comment by jdblischak** [comment]
> Yes, there will have to be a migration that takes place, with r-base 3.6 being dropped from conda-forge-pinning.

Good point @dpryan79! For context, the versions of r-base that conda-forge uses is controlled here:

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/27a89320e271d99be231e8b9074b514802880fae/recipe/conda_build_config.yaml#L634

> Is there more to it then that? Do we need to rebuild all the packages with R 4.1?

@izahn The hope is to get the bots to do as much of the work as possible once we get R 4.1 built :-)

**Comment by dpryan79** [comment]
The good news is that the bots did a LOT of work last time. That was the single easiest migration I've seen :)
