### ISSUE TITLE
r-base-3.2.2 does not pin to readline 6

### ISSUE THREAD

**Issue by vinjana** [conda-forge/r-base-feedstock#18]
Hi,

I have a problem with my bioconda packages for R that should build against r-base 3.2.2. The readline version 7.0 is pulled in instead of 6.2, against which r-base 3.2.2 is apparently build. See [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/252389187) for some example output from the bioconda build system.

Is r-base 3.2.2 discontinued? If not, how can I add the version pin to this repo -- it apparently starts at a 3.3 version!?

**Comment by johanneskoester** [comment]
Yes, we don't support older R versions. Rebuilding everything for an old version would be a huge effort. Can you update your package to build against r-base 3.3.2? Which package is it?

**Comment by vinjana** [comment]
The problem occurs for a number of packages in the pull request mentioned above. Apparently, bioconda tries building against r-base-3.2.2 in Travis. Maybe that should be changed!

**Comment by johanneskoester** [comment]
Bioconda-utils will use 3.3.2, unless something weird is going on. Maybe one of the dependencies explicitly pins to 3.2.2? Let's go on in the PR.
