### ISSUE TITLE
R-base 4.2 integration 

### ISSUE THREAD

**Issue by ZheFrench** [conda-forge/r-base-feedstock#209]
### Comment:

Hi ,

Does the r-base [4.2](https://cran.r-project.org/src/base/R-4/) will be available soon in conda  ? 

Is there a place to follow its integration in conda ?

Thanks ++

**Comment by cbrueffer** [comment]
See https://github.com/conda-forge/r-base-feedstock/issues/209

**Comment by ZheFrench** [comment]
see autoreference ?

**Comment by cbrueffer** [comment]
Oops, I pasted the wrong link in. See https://github.com/conda-forge/r-base-feedstock/pull/205 (pull request 205 in this feedstock).

**Comment by mjsteinbaugh** [comment]
https://github.com/conda-forge/r-base-feedstock/pull/205
