### ISSUE TITLE
m2 ssl is broken meaning that windows can't be rebuild

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/r-base-feedstock#214]
### Comment:

I don't have an actually issue for `m2-` packages, but I've experience that `m2-` ssl seems to be broken.

Downloading from `https` using `m2-` packages fails with an expired certificate:

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```

https://github.com/conda-forge/r-base-feedstock/pull/213#issuecomment-1180906204

conda-forge does not have a good way of maintaing `m2` packages. It is my opinion that they should be avoided if possible.

I believe that the actual fix, is removing the curl lines from https://github.com/jakirkham-feedstocks/r-base-feedstock/blob/skip_comp_activation/recipe/build-r-base.sh#L308=

and listing things as dependencies with associated sha256 hashes.

This should work around the ssl issues in `m2-`

cc: @jakirkham

**Comment by dhirschfeld** [comment]
Maybe just remove `m2-curl` altogether?
https://github.com/conda-forge/r-base-feedstock/blob/b4d9a0bad5ae38f7d003f34a6ad1ffa2a76b9f97/recipe/meta.yaml#L77

`curl` is part of the OS on any modern Windows:
```powershell
❯ get-command curl

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     curl.exe                                           7.83.1.0   C:\windows\system32\curl.exe
```

**Comment by hmaarrfk** [comment]
You are free to test this to ensure that it is true in our CIs. I'm just trying to help move this package forward by reducing the stringentness on the requirements. 

I don't have the bandwidth to work on this feedstock.

**Comment by isuruf** [comment]
As the error message says, it's as simple as adding `--insecure`. (If anybody is concerned about security they can send a PR to do this with conda-build's source and a checksum)

**Comment by jakirkham** [comment]
Enabling insecure builds doesn't sound like a good idea
