### ISSUE TITLE
BLAS variants ignored on osx-arm64

### ISSUE THREAD

**Issue by mfansler** [conda-forge/r-base-feedstock#249]
## Summary
Installing different Conda Forge `blas` variants has no effect on base R matrix operations performance. R uses the `lib/R/lib/Rblas.dylib` for BLAS operations, which appears to perform identically with our Netlib build of `libblas.dylib`.

Symlinking the `lib/R/lib/libRblas.dylib` to `../../libblas.dylib` enables R to use the BLAS variants.

## Initial Benchmarking
I ran some basic benchmarking tests to see how BLAS variants impact R performance on **osx-arm64** platform. I already know that [they impact Python `numpy`](https://stackoverflow.com/a/70241376/570918), with Accelerate making a huge difference. I was really surprised to find that **they all performed identically.**

**bench-prcomp.R**
```r
library(microbenchmark)

set.seed(20230506)
NROW=1000L
NCOL=1000L

mat <- matrix(rnorm(NROW*NCOL, 10), NROW, NCOL)

microbenchmark(prcomp(mat), times=10)
```

**Environments**
```bash
mamba create -n r42_accelerate r-base=4.2 r-microbenchmark 'blas=*=accelerate'
mamba create -n r42_netlib r-base=4.2 r-microbenchmark 'blas=*=netlib'
mamba create -n r42_openblas r-base=4.2 r-microbenchmark 'blas=*=openblas'
```

**Results**
```r
$ mamba run -n r42_accelerate Rscript bench-prcomp.R
Unit: seconds
        expr    min       lq     mean   median      uq      max neval
 prcomp(mat) 1.8176 1.824767 1.846034 1.828512 1.86154 1.927992    10

$ mamba run -n r42_netlib Rscript bench-prcomp.R
Unit: seconds
        expr      min       lq     mean  median       uq      max neval
 prcomp(mat) 1.819297 1.826732 1.843118 1.83046 1.868234 1.871313    10

$ mamba run -n r42_openblas Rscript bench-prcomp.R
Unit: seconds
        expr      min       lq     mean   median       uq      max neval
 prcomp(mat) 1.822875 1.823559 1.846244 1.831912 1.871775 1.886548    10
```

They are effectively identical, which is unexpected given that Accelerate is faster when used in NumPy.

## Modified Benchmarking
Next I modified each environment by replacing the `lib/R/lib/libRblas.dylib` with a symlink to `../../libblas.dylib`. This appears to give more expected results.

**Results**
```r
$ mamba run -n r42_accelerate Rscript bench-prcomp.R
Unit: milliseconds
        expr      min      lq     mean   median       uq      max neval
 prcomp(mat) 236.2402 238.195 258.9798 249.5734 281.4831 294.9549    10

$ mamba run -n r42_netlib Rscript bench-prcomp.R
Unit: seconds
        expr     min       lq     mean   median      uq      max neval
 prcomp(mat) 1.81474 1.827195 1.842966 1.829962 1.86686 1.873634    10

$ mamba run -n r42_openblas Rscript bench-prcomp.R
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
 prcomp(mat) 872.5037 912.5565 925.3458 929.6652 938.9488 989.4986    10
```

That is, OpenBLAS is 2X faster and Accelerate is 7X faster than the Netlib implementation, which appears to be what Conda Forge's R is delivering (at least for **osx-arm64**).

## Remarks
It is unclear whether this is intended, but I would expect not (hence the ![label: bug][~bug] label). It was discussed previously in #79, and changed in R 3.6.1 (https://github.com/conda-forge/r-base-feedstock/commit/a4b9e3f9349459a195bdfbfbdfa3ec5ccef4d150). To me it appears that using the `--with-blas=-lblas` flag in the build leads to R generating a `libRblas.dylib` using the available BLAS (which is `netlib` at build time) and this is not subsequently dynamic.

I'm unsure if this impacts other platforms. I'm also unsure if replacing with a symlink is stable. Perhaps someone knows why R still generates a `libRblas.dylib` despite the `-lblas` flag.

[~bug]: https://img.shields.io/badge/-bug-f00.svg

**Comment by isuruf** [comment]
Probably needs to set `r_cv_prog_fc_cc_compat_complex=1` before cross compiling for osx-arm64

**Comment by mfansler** [comment]
Just to add a little more documentation, the **osx-arm64** build abandons the external BLAS/LAPACK with:

```cpp
2023-06-16T08:28:48.7637240Z checking whether double complex BLAS can be used... no
2023-06-16T08:28:48.7656140Z configure: cannot use --with-lapack without --with-blas
2023-06-16T08:28:48.7659170Z configure: using internal LAPACK sources
```

which is in line with what Isuru recommended.
