### ISSUE TITLE
x64 builds on Windows seems to be broken

### ISSUE THREAD

**Issue by bgruening** [conda-forge/r-base-feedstock#26]
failing example PRs: https://github.com/conda-forge/staged-recipes/pull/4426 & https://github.com/conda-forge/staged-recipes/pull/4414

Here is a log:

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18743/job/j32vaun3opskjnav

This might be related to:
https://github.com/conda-forge/r-base-feedstock/pull/24

**Comment by mariusvniekerk** [comment]
Yeah seeing these too.

**Comment by ocefpaf** [comment]
:unamused: we need to pull the packages. But that is quite odd, we need to investigate why those pinnings are hurting Windows.

**Comment by bgruening** [comment]
With pull, you mean `remove`? It's only failing for 64bit afaik.

**Comment by ocefpaf** [comment]
> With pull, you mean `remove`? It's only failing for 64bit afaik.

Yep. I actually "moved" the Win x64 to the broken label. Let me know if that helped.
