### ISSUE TITLE
Add r-base version 3.5.0 to Linux aarch64

### ISSUE THREAD

**Issue by dingronghua** [conda-forge/r-base-feedstock#298]
### Package name

r

### Package version

3.5.0

### Package website

https://cloud.r-project.org/

### Package availability

https://cloud.r-project.org/src/base/R-3/R-3.5.0.tar.gz

### Additional comments

Currently, many Conda packages cannot be built on Linux arch64. In order to improve the conda Linux aarch64 ecosystem, we are committed to building the conda package for aarch64. However, when building most bioconductor - * packages, we are prompted that the unsatisfiable dependency relationship of platform Linux aarch64 is {'r base=3.5 '}. I hope that Conda forge can build this version of the Linux aarch64 Conda package. Thank you

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by mfansler** [comment]
Why such an old version? Other than pure R packages, no other packages would be available. Please elaborate why R 3.6 (which has **linux-aarch64** builds) is not sufficient.

**Comment by mfansler** [comment]
Maybe I can answer this myself. Seeing an unsatisfiable dependency ending with `r-base=3.5` is likely an artifact of the order of the path that the solver traverses when trying to find a solution. At least, that's the empirical sense I get after having seen this many times. The solver seems to first eliminate newer version combinations and ultimately reports the last thing it tried, which is a very old version. I expect that adding an `r-base=3.5` will not solve the problem, so, I'm going to close this.

However, I'd be happy to help with the actual problem - please add more details or link to where you are attempting a specific build. I'd recommend trying to manually create the failing environment using a newer Mamba/Micromamba - those tend to give better dependency conflict reports in my experience.
