### ISSUE TITLE
R include directory is not packaged anymore in 3.3.2

### ISSUE THREAD

**Issue by isuruf** [conda-forge/r-base-feedstock#30]
This happened after r-3.3.3 build number 6. build number 5 is fine.

cc @ocefpaf

**Comment by ocefpaf** [comment]
> This happened after r-3.3.3 build number 6. build number 5 is fine.

You mean r-3.3.2 bn 6, right? I'll remove the build 6 if someone hasn't done that already. Thanks!

**Comment by ocefpaf** [comment]
OK. We have only bn 0 and 1. I guess we had many unsuccessful builds with r-3.3.2 :smile:

**Comment by ocefpaf** [comment]
Build number 6 removed but this really complicates the use of R 3.3.2 b/c build number 5 has outdated pins. I don't want to invest time in fixing an old version of R.

@bgruening how important is R 3.3.2? Do you know what is necessary to fix it?
