### ISSUE TITLE
Rblas.dll and Rlapack.dll vendored in windows package

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/r-base-feedstock#331]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am confused by the fact the r-base appears to be vendoring BLAS and LAPACK instead of depending on it.

(There are two files called Rblas.dll and Rlapack.dll in `%CONDA_PREFIX%/lib/R/bin/x64`).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by isuruf** [comment]
`Rblas.dll` depends on `libblas.dll` and `Rlapack.dll` depends on `liblapack.dll`.

**Comment by SylvainCorlay** [comment]
Thanks.
