### ISSUE TITLE
Proposal: Drop support for R 3.3.2

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-base-feedstock#36]
## Summary

I propose we stop building conda-forge R packages for R 3.3.2.

cc: @conda-forge/r-base @isuruf 

## Motivation

* We are struggling to update the pins for R 3.3.2. If we can't update the pins, then we are unable to add some non-R dependencies for the recipes, which I consider one of the main advantages of using conda for R. I've made some attempts to patch R 3.3.2, but my efforts were motivated more by curiosity than any practical need: #28 #31 #32 #33

* R 3.3.2 is getting dated and more and more R packages don't even support it, e.g. [libcoin](https://cran.r-project.org/package=libcoin) and [uniqueAtomMat](https://github.com/conda-forge/r-uniqueatommat-feedstock/blob/master/recipe/meta.yaml#L27)

* The defaults channel is adding a dependency to all R packages (#34). Dropping support for R 3.3.2 packages will reduce the number that need to be rebuilt.

* I have gone through and rerendered all the R feedstocks that needed to be built for R 3.3.2 (with help from @rvalieris). Any R feedstock not built for R 3.3.2 at this point is because either it or a dependency is failing to build for a non-trivial reason.

* Based on the development patterns of the R core team, we can expect R 3.5.1 to be released near the end of June 2018, at which point we can start building the R packages for both 3.4.1 and 3.5.1.

## Actions to be taken

If we decide to drop support for R 3.3.2, we'll need to do the following:

- [x] Update [conda-forge-pinning-feedstock](https://github.com/conda-forge/conda-forge-pinning-feedstock) so that conda-smithy only builds packages for R 3.4.1. (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/28) ~~Update conda-smithy to only build R 3.4.1 (not sure how to do this since the [code I changed](https://github.com/conda-forge/conda-smithy/commit/94d7a7a017eac9f36f36854f7537d84f94976dd7#diff-3a2c4a048580db27ad9db93e2780b511) last time has been [deleted](https://github.com/conda-forge/conda-smithy/commit/3b115b1d7af868a5a472ea7a11892dae9f218350#diff-3a2c4a048580db27ad9db93e2780b511) in anticipation of the migration to cb3)~~
- [x] Drop R 3.3.2 from staged-recipes builds https://github.com/conda-forge/staged-recipes/pull/5274 ~~Update the `conda-build-all` commands in staged-recipes to use `r-base ==3.4.1` ([link](https://github.com/conda-forge/staged-recipes/search?q=r-base&type=Code&utf8=%E2%9C%93))~~
- [x] Delete the 3.3.2 branch of this repo

**Comment by jdblischak** [comment]
I know everyone is busy with the migration to conda-build 3, but I'd appreciate some feedback on this proposal. I need to know 2 things to be able to proceed:

1. Do you support dropping R 3.3.2? If yes, please +1 this Issue.
2. How can I update conda-smithy to drop R 3.3.2? Would it be possible to do a minor release, e.g. 2.4.5 -> 2.4.6, to make this small change prior to the cb3 migration? If it'd be preferred to update conda-smithy 3.*, I'd need to be shown where to make the change.

Thanks!

cc: @conda-forge/core @bgruening @isuruf @jakirkham

**Comment by isuruf** [comment]
I don't have an opinion about dropping 3.3.2.
To drop it with conda-smithy=3, you have to change the conda_build_config.yaml file in conda-forge-pinning package

**Comment by ocefpaf** [comment]
> 2. How can I update conda-smithy to drop R 3.3.2? Would it be possible to do a minor release, e.g. 2.4.5 -> 2.4.6, to make this small change prior to the cb3 migration? If it'd be preferred to update conda-smithy 3.*, I'd need to be shown where to make the change.

I'd say let's do that with cb3/

**Comment by jdblischak** [comment]
OK. I've submitted PRs to staged-recipes and the pinning feedstock:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/28
https://github.com/conda-forge/staged-recipes/pull/5325

**Comment by jdblischak** [comment]
Pinging a bunch of conda-forge R users (I skimmed the last month of PRs to staged-recipes). Do any of you still rely on support for R 3.3.2? We have been unable to build it with the latest conda-forge pinned dependencies. Please +1 this Issue if you are ok with this.

@ArneKr @bgruening @bsennblad @cbrueffer @daler @FrodePedersen @jenzopr @MathiasHaudgaard

**Comment by ocefpaf** [comment]
Thanks @jdblischak for doing this!

**Comment by cbrueffer** [comment]
I support dropping R 3.3.2; thanks for the initiative!

**Comment by bsennblad** [comment]
This should be fine! You got my support.

**Comment by jdblischak** [comment]
Great. Looks like everyone agrees on this change. The plan will be for it to go into effect once conda-smithy switches to conda-build 3.

**Comment by jdblischak** [comment]
@conda-forge/r-base Could one of the maintainers please delete the 3.3.2 branch? I don't have permission, and I couldn't find a way to submit a PR that deletes a branch.

**Comment by jakirkham** [comment]
Would it be better to merge that branch into `master` so the history is not lost?

**Comment by ericdill** [comment]
> Would it be better to merge that branch into master so the history is not lost?

Can this be done without rewriting the history of the master branch so as to not actually change the tip of master and force a rebuild?

**Comment by isuruf** [comment]
That branch never worked. (All the packages built from that branch were broken)

**Comment by jdblischak** [comment]
> Can this be done without rewriting the history of the master branch so as to not actually change the tip of master and force a rebuild?

I did a quick test merge locally, and this creates lots of merge conflicts.

There were only a few commits made on the 3.3.2 branch:

https://github.com/conda-forge/r-base-feedstock/compare/conda-forge:master...ericdill:3.3.2

Most are just updating the pins and other fiddling. The only one of interest (to me at least) was my patch to backport zlib support:

https://github.com/conda-forge/r-base-feedstock/commit/5c6666a6ed7e332d7bc2d9d92b479101dff41d88

But as @isuruf noted, despite successfully building, these packages still ended up being broken, so it was a short-lived success.

**Comment by jakirkham** [comment]
Yes, this can be done. Please see PR ( https://github.com/conda-forge/r-base-feedstock/pull/38 ).

It may not have worked, but it is still nice to have the history. Maybe there was some choice made that comes up again.

All I did was checkout Eric's copy of the branch merge with `master` and then overwrite everything in the merge commit with the contents of `master`. So it's a no-op commit that takes all the other changes along for the ride. :)

**Comment by jdblischak** [comment]
Now that conda-build 3 support has been merged into staged-recipes (https://github.com/conda-forge/staged-recipes/pull/5274), R 3.3.2 is no longer supported on conda-forge. Thanks everyone for your feedback and assistance!

And related, R 3.5.0 was released today, so R 3.5.1 is just a few months away.
