### ISSUE TITLE
R-base is not building with zlib 1.2.11

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/r-base-feedstock#4]
I can confirm that pinning to `zlib 1.2.8` still works.

Here is the error:

```
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking if zlib version >= 1.2.5... no
configure: error: zlib library and headers are required
checking whether zlib support suffices... Traceback (most recent call last):
```

See for the full log: https://circleci.com/gh/conda-forge/r-base-feedstock/3

xref: https://github.com/conda-forge/zlib-feedstock/pull/12/commits

**Comment by jdblischak** [comment]
For future reference, R 3.3.2 can be built with zlib 1.2.11 by applying the patch in https://github.com/conda-forge/r-base-feedstock/pull/28/commits/5c6666a6ed7e332d7bc2d9d92b479101dff41d88
