### ISSUE TITLE
Support MKL and other BLAS variants

### ISSUE THREAD

**Issue by sveinugu** [conda-forge/r-base-feedstock#79]
Issue:

Conda-forge now supports instaling MKL and other BLAS/LAPACK alternatives. As far as I can see, r-base has yet to take advantage of this.

See https://github.com/conda-forge/staged-recipes/issues/3022 and https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=blas#blas.

I am a bit of a newbie in the conda-forge github world, so this might be the wrong place to adress this issue (or it might have been adressed elsewhere).

**Comment by isuruf** [comment]
@mingwandroid, what do you think? I know that you had r-base's lapack and blas vendor openblas instead of using blas variants on defaults, but can't remember the reason for it

**Comment by isuruf** [comment]
https://github.com/conda-forge/r-base-feedstock/pull/80

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/r-base-feedstock/pull/89
