### ISSUE TITLE
Building _r-mutex in conda-forge

### ISSUE THREAD

**Issue by xhochy** [conda-forge/r-base-feedstock#83]
Currently, one needs the `r` channel in its channel list to able to install `r-base` from conda-forge. The backgound of why we have that is discussed in https://github.com/conda-forge/r-base-feedstock/issues/34

To make conda-forge a bit more self-contained, we could simply mirror https://github.com/AnacondaRecipes/aggregateR/blob/master/_r-mutex-feedstock/recipe/meta.yaml here.

Any opinions / objections?

**Comment by jakirkham** [comment]
cc @mingwandroid

**Comment by mingwandroid** [comment]
No objections from me. Kicking it up the ladder, @msarahan, have I overlooked anything?

**Comment by jdblischak** [comment]
I'm open to this, but a few notes:

1. Installing `r-base` from conda-forge does not require the r channel. The defaults channel is sufficient. I realize there is some overlap in these channels, but it's been noted that including the r channel greatly slows down the conda solver (and I can confirm this from personal experience). From testing older versions of conda, I can drop the r channel when installing r-base with conda version 4.3 and later.

1. Even if `_r-mutex` is available from conda-forge, it still won't be possible to install `r-base` without installing some packages from the defaults channel, e.g. `bwidget` and `tktable`

```
docker run --rm -it continuumio/miniconda3 bash
conda config --add channels defaults
conda config --add channels conda-forge
conda config --get channels
## --add channels 'defaults'   # lowest priority
## --add channels 'conda-forge'   # highest priority
conda config --set always_yes yes
conda update conda
conda --version
## conda 4.6.14
conda config --set channel_priority strict
conda update --all
conda install r-base
conda list | grep -v conda-forge
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
## _r-mutex                  1.0.0               anacondar_1  
## binutils_impl_linux-64    2.31.1               h6176602_1  
## binutils_linux-64         2.31.1               h6176602_7  
## bwidget                   1.9.11                        1  
## gfortran_impl_linux-64    7.3.0                hdf63c60_1  
## gfortran_linux-64         7.3.0                h553295d_7  
## libgcc-ng                 9.1.0                hdf63c60_0  
## libgfortran-ng            7.3.0                hdf63c60_0  
## libstdcxx-ng              9.1.0                hdf63c60_0  
## tktable                   2.10                 h14c3975_0 
```

**Comment by isuruf** [comment]
We should use only compiler runtimes and activation packages from defaults. Remaining packages are _r-mutex, tktable and bwidget. See also https://github.com/conda-forge/r-base-feedstock/issues/64

**Comment by xhochy** [comment]
@jdblischak For me it is looking like `_r-mutex` is in the R channel:

```
% conda search _r-mutex
Loading channels: done
# Name                       Version           Build  Channel
_r-mutex                       1.0.0     anacondar_1  pkgs/r
_r-mutex                       1.0.0           mro_2  pkgs/r
```

I only came across this as I'm working sometimes with a conda-mirror that only has defaults and conda-forge mirrored, not the R channel. If I misunderstood the notation in `conda search` here, feel free to correct me ;)

**Comment by isuruf** [comment]
@xhochy, defaults channel is an aggregation of pkgs/main, pkgs/r, pkgs/msys and others

**Comment by jdblischak** [comment]
> defaults channel is an aggregation of pkgs/main, pkgs/r, pkgs/msys and others

@isuruf Thanks for clarifying.

> I only came across this as I'm working sometimes with a conda-mirror that only has defaults and conda-forge mirrored, not the R channel.

@xhochy I see the confusion. My main point was to prevent you or any other user from explicitly listing the r channel. Since you are already doing that, there's nothing to worry about!

**Comment by fhoehle** [comment]
Hi @xhochy,  @mingwandroid, @jdblischak and @isuruf,

I'm having similar issues with institutions mirroring only anaconda and conda-forge. Favouring a more self-contained conda-forge channel I created PR: https://github.com/conda-forge/staged-recipes/pull/8646
Could you review/assist with that PR?

**Comment by isuruf** [comment]
_r-mutex is available now. Can somebody send a PR for bwidget and tktable?
