### ISSUE TITLE
Windows package is missing include, share, src, and tests directories

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/r-base-feedstock#9]
I believe that is the cause of the Windows failures like https://ci.appveyor.com/project/ocefpaf/staged-recipes/build/1.0.335/job/2a9m3aoxyq1o5qqa

@mingwandroid and @johanneskoester  the recipe seems to the almost identical to the one original one. Should we copy those files manually?

**Comment by johanneskoester** [comment]
Thanks!
