### ISSUE TITLE
Vanilla install pulls in pkgs/r/r with different version

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/r-base-feedstock#95]
Using `conda install -c conda-forge r=3.6` in a fresh environment installs `r` & `r-base` from different channels:
```
  r                  pkgs/r/linux-64::r-3.6.0-r36_0
  r-base             conda-forge/linux-64::r-base-3.6.1-h8900bf8_2
```

(for completeness: `conda install -c conda-forge r=3.6.1` fails with PackagesNotFoundError and `conda install -c conda-forge r` pulls everything for r=3.5.1 from conda-forge)

I'm guessing that https://github.com/conda-forge/r-feedstock needs to be rerendered?

BTW, there's more R-packages being pulled from `pkgs/{r,main}`:
```
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  r                  pkgs/r/linux-64::r-3.6.0-r36_0
  r-base             conda-forge/linux-64::r-base-3.6.1-h8900bf8_2
  r-boot             pkgs/r/noarch::r-boot-1.3_20-r36h6115d3f_0
  r-class            pkgs/r/linux-64::r-class-7.3_15-r36h96ca727_0
  r-cluster          pkgs/r/linux-64::r-cluster-2.0.8-r36ha65eedd_0
  r-codetools        pkgs/r/noarch::r-codetools-0.2_16-r36h6115d3f_0
  r-foreign          pkgs/main/linux-64::r-foreign-0.8_71-r36h96ca727_0
  r-kernsmooth       pkgs/r/linux-64::r-kernsmooth-2.23_15-r36ha65eedd_4
  r-lattice          conda-forge/linux-64::r-lattice-0.20_38-r36hcdcec82_1001
  r-mass             pkgs/r/linux-64::r-mass-7.3_51.3-r36h96ca727_0
  r-matrix           pkgs/r/linux-64::r-matrix-1.2_17-r36h96ca727_0
  r-mgcv             pkgs/r/linux-64::r-mgcv-1.8_28-r36h96ca727_0
  r-nlme             pkgs/main/linux-64::r-nlme-3.1_139-r36ha65eedd_0
  r-nnet             pkgs/main/linux-64::r-nnet-7.3_12-r36h96ca727_0
  r-recommended      pkgs/r/linux-64::r-recommended-3.6.0-r36_0
  r-rpart            pkgs/r/linux-64::r-rpart-4.1_15-r36h96ca727_0
  r-spatial          pkgs/main/linux-64::r-spatial-7.3_11-r36h96ca727_4
  r-survival         pkgs/r/linux-64::r-survival-2.44_1.1-r36h96ca727_0
  sed                conda-forge/linux-64::sed-4.7-h1bed415_1000
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
asn1crypto                0.24.0                py37_1003    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.5                    py37_0    conda-forge
conda-package-handling    1.3.11                   py37_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
libarchive                3.3.3             hb44662c_1005    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libxml2                   2.9.9                h13577e0_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-51-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by mingwandroid** [comment]
@h-vetinari, Is this using strict channel priority or not?

**Comment by isuruf** [comment]
We don't have packages built with R 3.6.1 yet. Will be done in the future.

**Comment by h-vetinari** [comment]
> @mingwandroid: @h-vetinari, Is this using strict channel priority or not?

It was done using the conda 4.7 default, so no. With `--strict-channel-priority`, it fails.

> @isuruf: We don't have packages built with R 3.6.1 yet. Will be done in the future.

It's a bit misleading though. R=3.6 has been out for a while, so it's a natural reflex to try to install it. Since conda-forge::r-base=3.6.1 has been merged already, this works, but may produce broken environments.

IOW, since `--strict-channel-priority` isn't the default for conda yet, the package-rerendering should be (relatively) a high priority, no? What's your idea about how long is "in the future"?

**Comment by mingwandroid** [comment]
@h-vetinari, we have spent a huge amount of time and energy to make sure that conda-forge and conda defaults are highly compatible, so while having some packages not yet present in conda-forge is unfortunate, the most important question, from my perspective, is does this collection of software work OK for you (clearly I'm not talking about the failure to come up with a solution).

If you want to ignore defaults entirely then that's completely cool too and we are making sure that `conda-forge` is self sufficient. I don't think we're there yet with `R`, but we're not far off.

**Comment by mingwandroid** [comment]
> but may produce broken environments.

When that happens it is now considered a bug, at least by the maintainers of `defaults`.

**Comment by h-vetinari** [comment]
@mingwandroid 
Yeah, there was no criticism, and it's cool how much has happened. I'm excited about the new BLAS-scheme and that the compatibility pinning is now on R-minor and not R-patch! :)

I was just starting out in trying to build an R=3.6 environment and haven't checked yet whether everything works or something is broken. I fully expected some of the packages I require would need rebuilds, but maybe not the R-install itself... I opened this issue because I had been sensitized by the longstanding warnings from the conda(-forge) people not to mix channels.

> When that happens it is now considered a bug, at least by the maintainers of `defaults`.

Great to hear! IIUC, conda/conda-forge are however still using different toolchains, are they not? Is it planned for conda to change to the conda-forge toolchain or vice versa?

**Comment by mingwandroid** [comment]
> IIUC, conda/conda-forge are however still using different toolchains, are they not?

We are not, no. There was a huge effort around the start ot the year to rebuild everything using the compilers our team maintian the recipes for.

**Comment by h-vetinari** [comment]
> @mingwandroid: We are not, no.

Very cool! Is that R-specific? Otherwise, I don't understand how conda-forge can't yet build (e.g.) scipy for windows, while conda does.

**Comment by mingwandroid** [comment]
No, it's across everything. You should probably compare our recipes (by "ours" I mean both AD and CF) and look for any differences. If you need help to understand them then I'd use a bit of `git blame` and ask the author.

**Comment by isuruf** [comment]
> No, it's across everything.

except for Fortran on windows

**Comment by mingwandroid** [comment]
Thanks for the correction @isuruf!

**Comment by h-vetinari** [comment]
> except for Fortran on windows

Which also explains the scipy case. Thanks for the info @mingwandroid @isuruf. :)

**Comment by mingwandroid** [comment]
Heh, indeed

**Comment by mingwandroid** [comment]
Thankfully we aim for a high degree of compatibility these days so you may be able to mix and match. ;-)

Over and out!
