### ISSUE TITLE
Default shared library extension is wrong(?) on OSX

### ISSUE THREAD

**Issue by dpryan79** [conda-forge/r-base-feedstock#98]
In the R 3.5.1 build, `.Platform$dynlib.ext` was set to `.so`, which worked because the shared libraries we ship tend to end in .so, regardless of the platform. Under the R 3.6.1 build, this got changed to the (presumably default) `.dylib`. That is then breaking things such as this PR: https://github.com/conda-forge/r-catboost-feedstock/pull/26

My guess is that this had previously been changed in one of the many patches.

**Comment by dbast** [comment]
Same/similar issue https://github.com/conda-forge/r-lightgbm-feedstock/pull/5

**Comment by isuruf** [comment]
We can't change this now, unless we recompile all R packages with C/C++/Fortran files.

**Comment by dpryan79** [comment]
Let's just keep this on the radar for the 3.7 release next year then. I don't personally care which of .so or .dylib are used, but since there are a number of errors I assume that conda-forge prefers .so files.

**Comment by dbast** [comment]
Also here https://github.com/conda-forge/r-rjags-feedstock/pull/8

**Comment by dbast** [comment]
Workaround used here: https://github.com/conda-forge/r-rjags-feedstock/pull/9

**Comment by isuruf** [comment]
Let's do this for 4.4? cc @mbargull

**Comment by mbargull** [comment]
I don't really follow.
IIUC, the proposal here was to revert back from the default to `.so` so that older patches/workarounds in feedstocks would still work.
Doesn't it make sense to stick to the default?
I'd assume it would make sense to search for patches/workarounds that change to `.so` in feedstocks and remove those in the migration, or doesn't it?
I'm lacking further insights in this to really tell what makes most sense for us.

**Comment by mbargull** [comment]
https://github.com/search?q=org%3Aconda-forge dynlib&type=code also only yields the `r-rjags` mentioned above.

**Comment by isuruf** [comment]
Reverting back to `.so` makes sense to me. Otherwise, you can't use pre-compiled R packages (that were compiled with system R) on macOS since the extensions end with `.so` instead of the conda-forge `.dylib`.

**Comment by mbargull** [comment]
Oh, I wasn't aware that they do that.
How do they build those packages? (Yep, I'm still a R noob.)
How do Homebrew/MacPorts handle this?
I don't see anything specific to that in https://github.com/Homebrew/homebrew-core/blob/be60fd12638d4c6afdb2ede2d99024cfdd06ab07/Formula/r/r.rb , https://github.com/macports/macports-ports/blob/e145a53ce0b18cea78b936d0a2571a612643196f/math/R/Portfile .

**Comment by mbargull** [comment]
Isuru answered this in gh-312 for me:
`conda-build` sets `SHLIB_EXT` which is how we override R's defaults.
(incredibly simple explanation I didn't consider :facepalm:)
